const fs = require('fs');
const dir = './src/locales';
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}

const translations = {
  en: {
    sidebar: { dashboard: "Dashboard", repositories: "Repositories", explore: "Explore", settings: "Settings" },
    dashboard: { greeting: "Welcome back,", subtitle: "Track, contribute, and manage open-source projects", totalRepos: "Verified Repos", active: "Active", completed: "Completed", openIssues: "Open Issues", recentRepos: "Recently Tracked Repos", viewAll: "View All", noRepos: "No repos tracked yet", addFirst: "Add your first repo to start tracking!", language: "Language" },
    repoForm: { updateRepo: "Update Repository", trackNew: "Track New Repo", updateDesc: "Refine repository details", trackDesc: "Enter details to start monitoring", repoName: "Repo Name", repoUrl: "Repository URL", language: "Language", priority: "Priority", exploring: "Exploring", active: "Active", completed: "Completed", notes: "Notes & Goals", notesPlaceholder: "Write down your tasks or goals...", saveChanges: "Save Changes", trackRepository: "Track Repository", verifyText: "Check if a repository exists and analyze its health" },
    repoList: { health: "Health", issues: "Issues", stars: "Stars", lastUpdated: "Last updated:", exploring: "Exploring", active: "Active", completed: "Completed", deleteConfirm: "Are you sure you want to remove this repository from tracking?", noActiveTitle: "No Active Workspace", noActiveDesc: "You haven't added any repositories to track yet. Use the form on the left to start monitoring your OSS contributions.", trackedRepos: "Tracked Repositories", total: "Total", unknown: "Unknown", lastActivity: "Last Activity", justNow: "Just now", added: "Added", apr2026: "Apr 2026", edit: "Edit", delete: "Delete" },
    login: { title: "Welcome Back", passwordMode: "PASSWORD", otpMode: "OTP CODE", emailPlaceholder: "Email address", passwordPlaceholder: "Password", signInButton: "Sign In", enterEmail: "Enter your email", getOtp: "Get Single-Use Code", verifyButton: "Verify & Enter", changeEmail: "Change Email", resendTimer: "Resend in {{time}}s", resendCode: "Resend Code", orContinue: "Or continue with", githubSignIn: "GitHub Sign In", noAccount: "Don't have an account?", registerHere: "Register here" },
    register: { title: "Create Account", verifyTitle: "Verify Email", subtitle: "Join to track your contributions", verifySubtitle: "Enter the 6-digit code sent to", username: "Username", emailPlaceholder: "Email address", passwordPlaceholder: "Password (min 6 chars)", sendOtp: "Send Verification Code", completeBtn: "Complete Registration", editDetails: "Edit Details", resendTimer: "Resend in {{time}}s", resendCode: "Resend Code", haveAccount: "Already have an account?", loginHere: "Login here" },
    landing: { navFeatures: "Features", navStats: "Stats", navPreview: "Preview", navSignIn: "Sign In", navGetStarted: "Get Started", badge: "The Modern Open Source Tracker", title1: "Track Your", typewriter: ["Open Source", "GitHub", "Contributions", "Impact"], title2: "Journey", subtitle: "Monitor commits, pull requests, and issues across repositories. Visualize your impact with stunning analytics and real-time sync.", startFree: "Start Tracking Free", viewDemo: "View Demo", builtFor1: "Built for", builtFor2: "Developers", featuresSub: "Powerful tools to track, analyze, and showcase your open source journey.", f1Title: "GitHub OAuth", f1Desc: "One-click secure authentication. Sync all your data in seconds.", f2Title: "Live Analytics", f2Desc: "Interactive Recharts dashboards. Commits, PRs, issues visualized.", f3Title: "Activity Heatmap", f3Desc: "GitHub-style contribution grid showing your coding rhythm.", f4Title: "JWT Security", f4Desc: "Enterprise-grade token authentication. Data encrypted end-to-end.", f5Title: "Instant Sync", f5Desc: "One-click pulls latest GitHub data and refreshes all metrics.", f6Title: "Multi-View Dashboard", f6Desc: "Dashboard, Repositories, and Analytics tabs. Collapsible sidebar.", stat1: "Commits Tracked", stat2: "Repositories", stat3: "Uptime", previewTitle1: "A dashboard that", previewTitle2: "inspires", navDashboard: "Dashboard", navAnalytics: "Analytics", f2Issues: "Issues", stat2Short: "Repos", activityGraph: "Activity Graph", ready1: "Ready to track your", ready2: "impact", join: "Join developers who visualize their open source journey with OSTracker.", getStartedNow: "Get Started Now" }
  },
  hi: {
    sidebar: { dashboard: "डैशबोर्ड", repositories: "रिपॉजिटरी", explore: "खोजें", settings: "सेटिंग्स" },
    dashboard: { greeting: "वापसी पर स्वागत है,", subtitle: "ओपन-सोर्स प्रोजेक्ट्स को ट्रैक और प्रबंधित करें", totalRepos: "सत्यापित रिपो", active: "सक्रिय", completed: "पूर्ण", openIssues: "खुले मुद्दे", recentRepos: "हाल की रिपॉजिटरी", viewAll: "सभी देखें", noRepos: "कोई रिपॉजिटरी ट्रैक नहीं की गई।", addFirst: "ट्रैक करना शुरू करने के लिए पहली रिपो जोड़ें!", language: "भाषा" },
    repoForm: { updateRepo: "रिपो अपडेट करें", trackNew: "नई रिपो ट्रैक करें", updateDesc: "विवरण परिष्कृत करें", trackDesc: "निगरानी शुरू करने के लिए विवरण दर्ज करें", repoName: "रिपो का नाम", repoUrl: "रिपॉजिटरी URL", language: "भाषा", priority: "प्राथमिकता", exploring: "खोज कर रहे हैं", active: "सक्रिय", completed: "पूर्ण", notes: "नोट्स और लक्ष्य", notesPlaceholder: "अपने कार्य या लक्ष्य लिखें...", saveChanges: "परिवर्तन सहेजें", trackRepository: "रिपॉजिटरी ट्रैक करें", verifyText: "जांचें कि रिपॉजिटरी मौजूद है या नहीं" },
    repoList: { health: "स्वास्थ्य", issues: "मुद्दे", stars: "स्टार्स", lastUpdated: "अंतिम अपडेट:", exploring: "खोज", active: "सक्रिय", completed: "पूर्ण", deleteConfirm: "क्या आप वाकई इस रिपॉजिटरी को हटाना चाहते हैं?", noActiveTitle: "कोई सक्रिय कार्यस्थान नहीं", noActiveDesc: "आपने अभी तक कोई रिपॉजिटरी नहीं जोड़ी है।", trackedRepos: "ट्रैक की गई रिपॉजिटरी", total: "कुल", unknown: "अज्ञात", lastActivity: "अंतिम गतिविधि", justNow: "अभी-अभी", added: "जोड़ा गया", apr2026: "अप्रैल 2026", edit: "संपादित करें", delete: "हटाएं" },
    login: { title: "वापसी पर स्वागत है", passwordMode: "पासवर्ड", otpMode: "ओटीपी कोड", emailPlaceholder: "ईमेल पता", passwordPlaceholder: "पासवर्ड", signInButton: "साइन इन करें", enterEmail: "अपना ईमेल दर्ज करें", getOtp: "कोड प्राप्त करें", verifyButton: "सत्यापित करें", changeEmail: "ईमेल बदलें", resendTimer: "{{time}}s में पुनः भेजें", resendCode: "पुनः भेजें", orContinue: "या इसके साथ जारी रखें", githubSignIn: "गिटहब के साथ साइन इन करें", noAccount: "खाता नहीं है?", registerHere: "यहां रजिस्टर करें" },
    register: { title: "खाता बनाएं", verifyTitle: "ईमेल सत्यापित करें", subtitle: "अपने योगदान ट्रैक करें", verifySubtitle: "भेजा गया 6-अंकीय कोड दर्ज करें:", username: "उपयोगकर्ता नाम", emailPlaceholder: "ईमेल पता", passwordPlaceholder: "पासवर्ड", sendOtp: "सत्यापन कोड भेजें", completeBtn: "पंजीकरण पूरा करें", editDetails: "विवरण संपादित करें", resendTimer: "{{time}}s में पुनः भेजें", resendCode: "पुनः भेजें", haveAccount: "पुराना खाता है?", loginHere: "लॉगिन करें" },
    landing: { navFeatures: "सुविधाएं", navStats: "आँकड़े", navPreview: "पूर्वावलोकन", navSignIn: "साइन इन", navGetStarted: "शुरू करें", badge: "आधुनिक ओपन-सोर्स ट्रैकर", title1: "ट्रैक करें अपनी", typewriter: ["ओपन-सोर्स", "गिटहब", "योगदान", "प्रभाव"], title2: "यात्रा", subtitle: "रिपॉजिटरी में कमिट, पीआर और मुद्दों की निगरानी करें। लाइव एनालिटिक्स के साथ अपना प्रभाव देखें।", startFree: "मुफ्त में ट्रैकिंग शुरू करें", viewDemo: "डेमो देखें", builtFor1: "बनाया गया है", builtFor2: "डेवलपर्स के लिए", featuresSub: "आपके ओपन-सोर्स सफर को ट्रैक, विश्लेषित और प्रदर्शित करने के शक्तिशाली उपकरण।", f1Title: "गिटहब ओथ", f1Desc: "एक क्लिक में सुरक्षित लॉगिन। कुछ सेकंड में अपना डेटा सिंक करें।", f2Title: "लाइव एनालिटिक्स", f2Desc: "इंटरैक्टिव डैशबोर्ड। कमिट, पीआर और मुद्दे विज़ुअलाइज़ करें।", f3Title: "गतिविधि हीटमैप", f3Desc: "गिटहब-जैसी कंट्रीब्यूशन ग्रिड।", f4Title: "JWT सुरक्षा", f4Desc: "उन्नत सुरक्षा और एन्क्रिप्शन।", f5Title: "त्वरित सिंक", f5Desc: "गिटहब से एक-क्लिक में रीयल-टाइम डेटा प्राप्त करें।", f6Title: "मल्टी-व्यू डैशबोर्ड", f6Desc: "डैशबोर्ड, रिपॉजिटरी और एनालिटिक्स।", stat1: "कमिट ट्रैक किए गए", stat2: "रिपॉजिटरी", stat3: "अपटाइम", previewTitle1: "एक डैशबोर्ड जो", previewTitle2: "प्रेरित करे", navDashboard: "डैशबोर्ड", navAnalytics: "एनालिटिक्स", f2Issues: "मुद्दे", stat2Short: "रिपो", activityGraph: "गतिविधि ग्राफ", ready1: "क्या आप तैयार हैं अपना", ready2: "प्रभाव ट्रैक करने के लिए", join: "दुनियां भर के डेवलपर्स के साथ जुड़ें और अपनी ओपन-सोर्स यात्रा विज़ुअलाइज़ करें।", getStartedNow: "अभी शुरू करें" }
  },
  es: {
    sidebar: { dashboard: "Panel", repositories: "Repositorios", explore: "Explorar", settings: "Ajustes" },
    dashboard: { greeting: "Bienvenido,", subtitle: "Rastrea y administra proyectos de código abierto", totalRepos: "Repos Verificados", active: "Activo", completed: "Completado", openIssues: "Problemas Abiertos", recentRepos: "Repositorios Recientes", viewAll: "Ver todo", noRepos: "No hay repositorios aún", addFirst: "¡Agrega tu primer repo para comenzar!", language: "Idioma" },
    repoForm: { updateRepo: "Actualizar Repo", trackNew: "Rastrear Nuevo", updateDesc: "Refinar detalles", trackDesc: "Ingresa detalles", repoName: "Nombre del Repo", repoUrl: "URL del Repositorio", language: "Idioma", priority: "Prioridad", exploring: "Explorando", active: "Activo", completed: "Completado", notes: "Notas y Metas", notesPlaceholder: "Escribe tus tareas...", saveChanges: "Guardar Cambios", trackRepository: "Rastrear Repo", verifyText: "Verifica si existe el repositorio y su estado" },
    repoList: { health: "Salud", issues: "Asuntos", stars: "Estrellas", lastUpdated: "Última actualización:", exploring: "Explorando", active: "Activo", completed: "Completado", deleteConfirm: "¿Estás seguro de que quieres eliminar este repositorio del seguimiento?", noActiveTitle: "Sin espacio activo", noActiveDesc: "No has añadido repositorios para rastrear aún.", trackedRepos: "Repositorios rastreados", total: "Total", unknown: "Desconocido", lastActivity: "Última actividad", justNow: "Justo ahora", added: "Añadido", apr2026: "Abr 2026", edit: "Editar", delete: "Eliminar" },
    login: { title: "Bienvenido de nuevo", passwordMode: "CONTRASEÑA", otpMode: "CÓDIGO OTP", emailPlaceholder: "Dirección de correo", passwordPlaceholder: "Contraseña", signInButton: "Iniciar sesión", enterEmail: "Ingresa correo", getOtp: "Recibir Código", verifyButton: "Verificar y Entrar", changeEmail: "Cambiar Correo", resendTimer: "Reenviar en {{time}}s", resendCode: "Reenviar", orContinue: "O continuar con", githubSignIn: "Iniciar con GitHub", noAccount: "¿No tienes cuenta?", registerHere: "Regístrate aquí" },
    register: { title: "Crear Cuenta", verifyTitle: "Verificar Correo", subtitle: "Únete para rastrear contribuciones", verifySubtitle: "Ingresa el código que te enviamos", username: "Usuario", emailPlaceholder: "Correo", passwordPlaceholder: "Contraseña (min 6 chars)", sendOtp: "Enviar código", completeBtn: "Completar Registro", editDetails: "Editar", resendTimer: "Reenviar en {{time}}s", resendCode: "Reenviar", haveAccount: "¿Ya tienes cuenta?", loginHere: "Inicia sesión" },
    landing: { navFeatures: "Características", navStats: "Estadísticas", navPreview: "Vista Previa", navSignIn: "Entrar", navGetStarted: "Comenzar", badge: "El Rastreador de Código Abierto Moderno", title1: "Rastrea tu", typewriter: ["Código Abierto", "GitHub", "Contribuciones", "Impacto"], title2: "Viaje", subtitle: "Monitorea commits, pull requests y problemas en repositorios. Visualiza tu impacto con análisis asombrosos y sincronización en tiempo real.", startFree: "Comenzar gratis", viewDemo: "Ver Demo", builtFor1: "Diseñado para", builtFor2: "Desarrolladores", featuresSub: "Poderosas herramientas para rastrear, analizar y mostrar tu viaje en código abierto.", f1Title: "Autenticación de GitHub", f1Desc: "Inicio de sesión seguro con un clic. Sincroniza todos tus datos en segundos.", f2Title: "Análisis en Vivo", f2Desc: "Paneles interactivos Recharts. Commits, PRs, problemas visualizados.", f3Title: "Mapa de Calor de Actividad", f3Desc: "Cuadrícula de contribución al estilo GitHub que muestra tu ritmo de codificación.", f4Title: "Seguridad JWT", f4Desc: "Autenticación con tokens de nivel empresarial. Datos cifrados.", f5Title: "Sincronización Instantánea", f5Desc: "Obtén datos de GitHub con un clic y actualiza todas las métricas.", f6Title: "Panel Multivista", f6Desc: "Panel, Repositorios y Análisis. Barra lateral.", stat1: "Commits Rastreos", stat2: "Repositorios", stat3: "Disponibilidad", previewTitle1: "Un panel que", previewTitle2: "inspira", navDashboard: "Panel", navAnalytics: "Análisis", f2Issues: "Asuntos", stat2Short: "Repos", activityGraph: "Gráfico de Actividad", ready1: "¿Listo para rastrear tu", ready2: "impacto", join: "Únete a los desarrolladores que visualizan su viaje de código abierto con OSTracker.", getStartedNow: "Comienza Ahora" }
  },
  fr: {
    sidebar: { dashboard: "Tableau", repositories: "Dépôts", explore: "Explorer", settings: "Paramètres" },
    dashboard: { greeting: "Bienvenue,", subtitle: "Suivez et gérez des projets open-source", totalRepos: "Dépôts Vérifiés", active: "Actif", completed: "Terminé", openIssues: "Questions Ouvertes", recentRepos: "Dépôts Récents", viewAll: "Voir tout", noRepos: "Aucun dépôt trouvé", addFirst: "Ajoutez votre premier dépôt!", language: "Langue" },
    repoForm: { updateRepo: "Mettre à jour", trackNew: "Nouveau Dépôt", updateDesc: "Affiner les détails", trackDesc: "Entrez les détails pour suivre", repoName: "Nom", repoUrl: "URL", language: "Langue", priority: "Priorité", exploring: "Exploration", active: "Actif", completed: "Terminé", notes: "Notes et Objectifs", notesPlaceholder: "Écrivez vos tâches...", saveChanges: "Sauvegarder", trackRepository: "Suivre le Dépôt", verifyText: "Vérifiez la santé du projet" },
    repoList: { health: "Santé", issues: "Problèmes", stars: "Étoiles", lastUpdated: "Dernière mise à jour:", exploring: "Exploration", active: "Actif", completed: "Terminé", deleteConfirm: "Voulez-vous vraiment supprimer ce dépôt du suivi?", noActiveTitle: "Aucun espace actif", noActiveDesc: "Vous n'avez pas encore ajouté de dépôts à suivre.", trackedRepos: "Dépôts suivis", total: "Total", unknown: "Inconnu", lastActivity: "Dernière activité", justNow: "A l'instant", added: "Ajouté", apr2026: "Avr 2026", edit: "Modifier", delete: "Supprimer" },
    login: { title: "Bon retour", passwordMode: "MOT DE PASSE", otpMode: "CODE OTP", emailPlaceholder: "Email", passwordPlaceholder: "Mot de passe", signInButton: "Connexion", enterEmail: "Entrez email", getOtp: "Recevoir le Code", verifyButton: "Vérifier", changeEmail: "Changer email", resendTimer: "Renvoyer {{time}}s", resendCode: "Renvoyer", orContinue: "Ou continuer avec", githubSignIn: "GitHub", noAccount: "Pas de compte?", registerHere: "S'inscrire" },
    register: { title: "Nouveau Compte", verifyTitle: "Vérifier l'email", subtitle: "Suivez vos projets", verifySubtitle: "Entrez le code envoyé à", username: "Nom d'utilisateur", emailPlaceholder: "Email", passwordPlaceholder: "Mot de passe", sendOtp: "Envoyer le Code", completeBtn: "Terminer", editDetails: "Éditer", resendTimer: "Renvoyer {{time}}s", resendCode: "Renvoyer", haveAccount: "Vous avez un compte?", loginHere: "Connecte toi" },
    landing: { navFeatures: "Caractéristiques", navStats: "Sats", navPreview: "Aperçu", navSignIn: "Se connecter", navGetStarted: "Commencer", badge: "Le Tracker Open Source Moderne", title1: "Suivez votre", typewriter: ["Open Source", "GitHub", "Contributions", "Impact"], title2: "Voyage", subtitle: "Surveillez les commits, les pull requests et les problèmes. Visualisez votre impact avec des analyses.", startFree: "Commencer gratuitement", viewDemo: "Voir Démo", builtFor1: "Conçu pour", builtFor2: "Développeurs", featuresSub: "Des outils puissants pour suivre et présenter votre parcours.", f1Title: "GitHub OAuth", f1Desc: "Authentification via GitHub.", f2Title: "Analytique", f2Desc: "Tableaux de bord interactifs.", f3Title: "Activité Heatmap", f3Desc: "Grille de contribution de style GitHub.", f4Title: "Sécurité JWT", f4Desc: "Sécurisé de bout en bout.", f5Title: "Synchronisation Instantanée", f5Desc: "Obtenez des données de GitHub.", f6Title: "Tableau de Bord", f6Desc: "Barre latérale rétractable.", stat1: "Commits Suivis", stat2: "Dépôts", stat3: "Disponibilité", previewTitle1: "Un tableau de bord qui", previewTitle2: "inspire", navDashboard: "Tableau", navAnalytics: "Analytique", f2Issues: "Problèmes", stat2Short: "Dépôts", activityGraph: "Graphe d'activité", ready1: "Prêt à suivre votre", ready2: "impact", join: "Rejoignez.", getStartedNow: "Commencer maintenant" }
  },
  ja: {
    sidebar: { dashboard: "ダッシュボード", repositories: "リポジトリ", explore: "探検", settings: "設定" },
    dashboard: { greeting: "おかえりなさい、", subtitle: "プロジェクトの追跡", totalRepos: "検証済みリポジトリ", active: "アクティブ", completed: "完了", openIssues: "未解決の問題", recentRepos: "最近のリポジトリ", viewAll: "すべて", noRepos: "データがありません", addFirst: "追加を開始してください", language: "言語" },
    repoForm: { updateRepo: "更新", trackNew: "新規追跡", updateDesc: "詳細を修正", trackDesc: "詳細を入力", repoName: "名前", repoUrl: "URL", language: "言語", priority: "優先度", exploring: "探索中", active: "アクティブ", completed: "完了", notes: "メモ", notesPlaceholder: "タスクを書く...", saveChanges: "保存", trackRepository: "追跡する", verifyText: "AI 検証" },
    repoList: { health: "健康", issues: "問題", stars: "スター", lastUpdated: "最終更新:", exploring: "探索中", active: "アクティブ", completed: "完了", deleteConfirm: "追跡リストからこのリポジトリを削除してもよろしいですか？", noActiveTitle: "アクティブな作業がありません", noActiveDesc: "リポジトリがまだ追加されていません。", trackedRepos: "追跡されたリポジトリ", total: "合計", unknown: "未知", lastActivity: "最後のアクティビティ", justNow: "たった今", added: "追加された", apr2026: "2026年4月", edit: "編集", delete: "削除" },
    login: { title: "おかえりなさい", passwordMode: "パスワード", otpMode: "ワンタイムコード", emailPlaceholder: "メール", passwordPlaceholder: "パスワード", signInButton: "サインイン", enterEmail: "メールを入力", getOtp: "コードを取得", verifyButton: "確認", changeEmail: "メールを変える", resendTimer: "{{time}}秒後", resendCode: "再送信", orContinue: "または", githubSignIn: "GitHubで接続", noAccount: "未登録ですか？", registerHere: "登録" },
    register: { title: "アカウント作成", verifyTitle: "メール確認", subtitle: "貢献を追跡しましょう", verifySubtitle: "送信されたコードを入力:", username: "ユーザー名", emailPlaceholder: "メール", passwordPlaceholder: "パスワード", sendOtp: "送信", completeBtn: "完了", editDetails: "編集", resendTimer: "再送信 {{time}}s", resendCode: "再送", haveAccount: "アカウントあり？", loginHere: "ログイン" },
    landing: { navFeatures: "機能", navStats: "統計", navPreview: "プレビュー", navSignIn: "サインイン", navGetStarted: "開始する", badge: "現代のオープンソーストラッカー", title1: "あなたの", typewriter: ["オープンソース", "GitHub", "貢献", "影響"], title2: "を追跡する", subtitle: "コミット、プルリクエスト、問題などを追跡。", startFree: "無料で追跡開始", viewDemo: "デモを見る", builtFor1: "ために作られた", builtFor2: "開発者", featuresSub: "オープンソースの旅を...", f1Title: "GitHub OAuth", f1Desc: "ワンクリック認証。", f2Title: "ライブアナリティクス", f2Desc: "インタラクティブなダッシュボード。", f3Title: "ヒートマップ", f3Desc: "コーディングリズム。", f4Title: "JWTセキュリティ", f4Desc: "企業のセキュリティ。", f5Title: "リアルタイム同期", f5Desc: "データを即更新。", f6Title: "マルチビュー", f6Desc: "設定可能なUI。", stat1: "追跡コミット", stat2: "リポジトリ", stat3: "稼働時間", previewTitle1: "インスピレーションを与える", previewTitle2: "ダッシュボード", navDashboard: "ダッシュボード", navAnalytics: "分析", f2Issues: "問題", stat2Short: "リポジトリ", activityGraph: "活動グラフ", ready1: "あなたの", ready2: "影響", join: "OSTrackerに参加する。", getStartedNow: "今すぐ始める" }
  },
  ta: {
    sidebar: { dashboard: "முகப்பு", repositories: "கிடங்குகள்", explore: "ஆராய்", settings: "அமைப்புகள்" },
    dashboard: { greeting: "வரவேற்பு", subtitle: "திட்டங்களைக் கண்காணி", totalRepos: "சரிபார்க்கப்பட்டவை", active: "செயலில்", completed: "முடிந்தது", openIssues: "சிக்கல்கள்", recentRepos: "சமீபத்தியவை", viewAll: "அனைத்தும்", noRepos: "கிடங்குகள் இல்லை", addFirst: "தொடங்கவும்!", language: "மொழி" },
    repoForm: { updateRepo: "புதுப்பி", trackNew: "புதியது", updateDesc: "விவரங்களைச் செம்மைப்படுத்து", trackDesc: "உள்ளிடு", repoName: "பெயர்", repoUrl: "URL", language: "மொழி", priority: "முன்னுரிமை", exploring: "ஆராய்கிறது", active: "செயலில்", completed: "முடிந்தது", notes: "குறிப்புகள்", notesPlaceholder: "எழுதுங்கள்...", saveChanges: "சேமி", trackRepository: "கண்காணி", verifyText: "சோதிக்கவும்" },
    repoList: { health: "சுகாதாரம்", issues: "சிக்கல்கள்", stars: "நட்சத்திரங்கள்", lastUpdated: "புதுப்பிக்கப்பட்டது:", exploring: "ஆராய்கிறது", active: "செயலில்", completed: "முடிந்தது", deleteConfirm: "நீக்க வேண்டுமா?", noActiveTitle: "கிடங்குகள் ஏதுமில்லை", noActiveDesc: "நீங்கள் இன்னும் எந்த கிடங்குகளையும் சேர்க்கவில்லை.", trackedRepos: "கண்காணிக்கப்படும் கிடங்குகள்", total: "மொத்தம்", unknown: "தெரியவில்லை", lastActivity: "கடைசி செயல்பாடு", justNow: "இப்போது", added: "சேர்க்கப்பட்டது", apr2026: "ஏப் 2026", edit: "திருத்து", delete: "நீக்கு" },
    login: { title: "வரவேற்பு", passwordMode: "கடவுச்சொல்", otpMode: "OTP", emailPlaceholder: "மின்னஞ்சல்", passwordPlaceholder: "கடவுச்சொல்", signInButton: "உள்நுழை", enterEmail: "மின்னஞ்சல்", getOtp: "குறியீடு பெறுக", verifyButton: "சரிபார்", changeEmail: "மாற்று", resendTimer: "{{time}}s", resendCode: "மீண்டும்", orContinue: "அல்லது", githubSignIn: "GitHub", noAccount: "கணக்கு இல்லையா?", registerHere: "பதிவு செய்" },
    register: { title: "உருவாக்கு", verifyTitle: "சரிபார்", subtitle: "சேரவும்", verifySubtitle: "குறியீட்டை உள்ளிடவும்", username: "பெயர்", emailPlaceholder: "மின்னஞ்சல்", passwordPlaceholder: "கடவுச்சொல்", sendOtp: "அனுப்பு", completeBtn: "முழுமை", editDetails: "திருத்து", resendTimer: "{{time}}s", resendCode: "மீண்டும்", haveAccount: "கணக்கு உள்ளதா?", loginHere: "உள்நுழை" },
    landing: { navFeatures: "அம்சங்கள்", navStats: "புள்ளிவிவரங்கள்", navPreview: "முன்னோட்டம்", navSignIn: "உள்நுழை", navGetStarted: "தொடங்கவும்", badge: "The Modern Open Source Tracker", title1: "உங்கள்", typewriter: ["Open Source", "பங்களிப்பு", "தாக்கம்", "GitHub"], title2: "கண்காணி", subtitle: "commits, pull requests கண்காணிக்கவும். லைவ் അനலிடிக்ஸ் மூலம் உங்கள் தாக்கத்தை விவாதிக்கவும்.", startFree: "தொடங்கு", viewDemo: "Demo பார்க்கவும்", builtFor1: "உருவாக்கப்பட்டது", builtFor2: "டெவலப்பர்களுக்காக", featuresSub: "சக்திவாய்ந்த கருவிகள்.", f1Title: "GitHub OAuth", f1Desc: "விவரங்களை பாதுகாப்பாக ஒத்திசைக்கவும்.", f2Title: "லைவ் அனலிடிக்ஸ்", f2Desc: "Recharts dashboards.", f3Title: "ஹூட்மாப்", f3Desc: "GitHub மாதிரியான கிரிட்.", f4Title: "JWT Security", f4Desc: "பாதுகாப்பான பரிமாற்றம்.", f5Title: "Instant Sync", f5Desc: "தரவு ஒத்திசைவு.", f6Title: "முழு முகப்பு", f6Desc: "பகுப்பாய்வு தளம்.", stat1: "கண்காணிக்கப்பட்டவை", stat2: "கிடங்குகள்", stat3: "நேரம்", previewTitle1: "உங்களுக்காக", previewTitle2: "ஒரு முகப்பு", navDashboard: "முகப்பு", navAnalytics: "அனலிடிக்ஸ்", f2Issues: "சிக்கல்கள்", stat2Short: "கிடங்குகள்", activityGraph: "வரைபடம்", ready1: "நீங்கள் தயாரா?", ready2: "இப்போது", join: "OSTracker அப்ளிகேஷனை முயற்சிக்கவும்.", getStartedNow: "தொடங்குக" }
  },
  te: {
    sidebar: { dashboard: "డాష్‌బోర్డ్", repositories: "రిపోజిటరీలు", explore: "అన్వేషించండి", settings: "సెట్టింగ్‌లు" },
    dashboard: { greeting: "స్వాగతం", subtitle: "ప్రాజెక్ట్‌లను నిర్వహించండి", totalRepos: "ధృవీకరించిన రిపోలు", active: "క్రియాశీల", completed: "పూర్తయింది", openIssues: "సమస్యలు", recentRepos: "ఇటీవలి పరిమాణాలు", viewAll: "అన్నీ చూడండి", noRepos: "సమాచారం లేదు", addFirst: "మొదటి సారి జోడించండి!", language: "భాష" },
    repoForm: { updateRepo: "నవీకరించండి", trackNew: "కొత్త రిపో", updateDesc: "అప్‌డేట్ చేయండి", trackDesc: "రాయండి", repoName: "రిపో పేరు", repoUrl: "URL", language: "భాష", priority: "ప్రాధాన్యత", exploring: "అన్వేషిస్తోంది", active: "క్రియాశీల", completed: "పూర్తయింది", notes: "గమనికలు", notesPlaceholder: "రాయండి...", saveChanges: "సేవ్ చేయండి", trackRepository: "ట్రాక్ చేయండి", verifyText: "సరి చూడండి" },
    repoList: { health: "ఆరోగ్యం", issues: "సమస్యలు", stars: "నక్షత్రాలు", lastUpdated: "చివరి అప్‌డేట్:", exploring: "అన్వేషిస్తోంది", active: "క్రియాశీల", completed: "పూర్తయింది", deleteConfirm: "మీరు ఖచ్చితంగా తొలగించాలనుకుంటున్నారా?", noActiveTitle: "స్థలం లేదు", noActiveDesc: "మీరు ఎలాంటి రిపోలు జోడించలేదు.", trackedRepos: "ట్రాక్ చేసిన రిపోలు", total: "మొత్తం", unknown: "తెలియదు", lastActivity: "చివరి పని", justNow: "ఇప్పుడే", added: "జోడించబడింది", apr2026: "ఏప్రిల్ 2026", edit: "సవరించు", delete: "తొలగించు" },
    login: { title: "తిరిగి స్వాగతం", passwordMode: "పాస్వర్డ్", otpMode: "OTP నియమం", emailPlaceholder: "ఇమెయిల్", passwordPlaceholder: "పాస్వర్డ్", signInButton: "సైన్ ఇన్ చేయండి", enterEmail: "ఇమెయిల్", getOtp: "కోడ్ పొందండి", verifyButton: "ధృవీకరించు", changeEmail: "ఇమెయిల్ మార్చు", resendTimer: "{{time}}s", resendCode: "మళ్ళీ పంపు", orContinue: "లేదా", githubSignIn: "GitHub", noAccount: "ఖాతా లేదా?", registerHere: "సైన్ అప్" },
    register: { title: "సృష్టించండి", verifyTitle: "సరి చూడండి", subtitle: "చేరండి", verifySubtitle: "కోడ్ ఎంటర్ చేయండి", username: "పేరు", emailPlaceholder: "ఇమెయిల్", passwordPlaceholder: "పాస్వర్డ్", sendOtp: "పంపు", completeBtn: "పూర్తి", editDetails: "సవరించు", resendTimer: "{{time}}s", resendCode: "మళ్ళీ పంపు", haveAccount: "ఖాతా ఉందా?", loginHere: "లాగిన్ చేయండి" },
    landing: { navFeatures: "లక్షణాలు", navStats: "గణాంకాలు", navPreview: "ప్రివ్యూ", navSignIn: "సైన్ ఇన్", navGetStarted: "ప్రారంభించండి", badge: "The Modern Open Source Tracker", title1: "మీ", typewriter: ["ఆధారం", "GitHub", "సహకారం", "ప్రభావం"], title2: "ప్రయాణని", subtitle: "commits మరియు PRలు ట్రాక్ చేయండి.", startFree: "ఉచితంగా ప్రారంభించండి", viewDemo: "డెమో చూడండి", builtFor1: "డెవలపర్ల", builtFor2: "కోసం", featuresSub: "మంచి సాధనాలు ఇక్కడ ఉన్నాయి.", f1Title: "GitHub OAuth", f1Desc: "ఖచ్చితమైన లాగిన్.", f2Title: "లైవ్ ఎనాలిటిక్స్", f2Desc: "నిజ-సమయ గణాంకాలు.", f3Title: "హీట్‌మ్యాప్", f3Desc: "కంట్రిబ్యూషన్ గ్రిడ్.", f4Title: "JWT సెక్యూరిటీ", f4Desc: "భద్రత.", f5Title: "తక్షణ సింక్", f5Desc: "డేటా మార్పులు.", f6Title: "డాష్‌బోర్డ్", f6Desc: "మంచి UI.", stat1: "కమిట్స్", stat2: "రిపోలు", stat3: "అప్‌టైమ్", previewTitle1: "అద్భుతమైన", previewTitle2: "డాష్‌బోర్డ్", navDashboard: "డాష్‌బోర్డ్", navAnalytics: "ఎనాలిటిక్స్", f2Issues: "సమస్యలు", stat2Short: "రిపోలు", activityGraph: "ఆక్టివిటీ గ్రాఫ్", ready1: "మీరు", ready2: "సిద్ధంగా ఉన్నారా?", join: "OSTracker తో చేరండి.", getStartedNow: "ఇప్పుడే ప్రారంభించండి" }
  },
  or: {
    sidebar: { dashboard: "ଡ୍ୟାସବୋର୍ଡ", repositories: "ରିପୋଜିଟୋରୀ", explore: "ଅନୁସନ୍ଧାନ କରନ୍ତୁ", settings: "ସେଟିଂସ" },
    dashboard: { greeting: "ସ୍ୱାଗତ,", subtitle: "ପ୍ରୋଜେକ୍ଟ ପରିଚାଳନା କରନ୍ତୁ", totalRepos: "ଯାଞ୍ଚ ହୋଇଥିବା ରିପୋ", active: "ସକ୍ରିୟ", completed: "ସମ୍ପୂର୍ଣ୍ଣ", openIssues: "ଖୋଲା ସମସ୍ୟାଗୁଡିକ", recentRepos: "ସାମ୍ପ୍ରତିକ ରିପୋଜିଟୋରୀ", viewAll: "ସବୁ ଦେଖନ୍ତୁ", noRepos: "ଖୋଜି ମିଳିଲା ନାହିଁ", addFirst: "ଆରମ୍ଭ କରନ୍ତୁ!", language: "ଭାଷା" },
    repoForm: { updateRepo: "ଅପଡେଟ୍ କରନ୍ତୁ", trackNew: "ନୂଆ ରିପୋ ଟ୍ରାକ୍ କରନ୍ତୁ", updateDesc: "ବିବରଣୀ ସୁଧାରନ୍ତୁ", trackDesc: "ବିବରଣୀ ଦିଅନ୍ତୁ", repoName: "ରିପୋ ନାମ", repoUrl: "ରିପୋ URL", language: "ଭାଷା", priority: "ପ୍ରାଥମିକତା", exploring: "ଅନୁସନ୍ଧାନ", active: "ସକ୍ରିୟ", completed: "ସମ୍ପୂର୍ଣ୍ଣ", notes: "ନୋଟ୍ସ", notesPlaceholder: "ଆପଣଙ୍କର ଲକ୍ଷ୍ୟ ଲେଖନ୍ତୁ...", saveChanges: "ସେଭ୍ କରନ୍ତୁ", trackRepository: "ଟ୍ରାକ୍ କରନ୍ତୁ", verifyText: "ଦୟାକରି ଯାଞ୍ଚ କରନ୍ତୁ" },
    repoList: { health: "ସ୍ୱାସ୍ଥ୍ୟ", issues: "ସମସ୍ୟାଗୁଡିକ", stars: "ଷ୍ଟାର୍ସ", lastUpdated: "ଶେଷ ଅପଡେଟ୍:", exploring: "ଅନୁସନ୍ଧାନ", active: "ସକ୍ରିୟ", completed: "ସମ୍ପୂର୍ଣ୍ଣ", deleteConfirm: "ଆପଣ ନିଶ୍ଚିତ କି?", noActiveTitle: "କୌଣସି ପ୍ରୋଜେକ୍ଟ ନାହିଁ", noActiveDesc: "ଆପଣ କୌଣସି ପ୍ରୋଜେକ୍ଟ ଯୋଡି ନାହାଁନ୍ତି।", trackedRepos: "ଟ୍ରାକ୍ କରାଯାଉଥିବା ରିପୋଜିଟୋରୀ", total: "ସମୁଦାୟ", unknown: "ଅଜ୍ଞାତ", lastActivity: "ଶେଷ କାର୍ଯ୍ୟ", justNow: "ବର୍ତ୍ତମାନ", added: "ଯୋଡାଗଲା", apr2026: "ଏପ୍ରିଲ୍ 2026", edit: "ସମ୍ପାଦନ", delete: "ଡିଲିଟ୍" },
    login: { title: "ସ୍ୱାଗତ", passwordMode: "ପାସୱାର୍ଡ", otpMode: "OTP ଗୁପ୍ତକୋଡ", emailPlaceholder: "ଇମେଲ୍", passwordPlaceholder: "ପାସୱାର୍ଡ", signInButton: "ସାଇନ୍ ଇନ୍", enterEmail: "ଇମେଲ୍ ଏଣ୍ଟର୍", getOtp: "କୋଡ୍ ଆଣନ୍ତୁ", verifyButton: "ପ୍ରମାଣିତ", changeEmail: "ବଦଳାନ୍ତୁ", resendTimer: "{{time}}s", resendCode: "ପୁନର୍ବାର ପଠାନ୍ତୁ", orContinue: "କିମ୍ବା", githubSignIn: "ଗିଟହବ", noAccount: "ଖାତା ନାହିଁ?", registerHere: "ଏଠାରେ ପଞ୍ଜିକରଣ କରନ୍ତୁ" },
    register: { title: "ଖାତା ତିଆରି କରନ୍ତୁ", verifyTitle: "ଯାଞ୍ଚ", subtitle: "ଯୋଗ ଦିଅନ୍ତୁ", verifySubtitle: "କୋଡ୍ ଏଣ୍ଟର୍ କରନ୍ତୁ", username: "ନାମ", emailPlaceholder: "ଇମେଲ୍", passwordPlaceholder: "ପାସୱାର୍ଡ", sendOtp: "ପଠାନ୍ତୁ", completeBtn: "ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ", editDetails: "ସମ୍ପାଦନ", resendTimer: "{{time}}s", resendCode: "ପୁନର୍ବାର", haveAccount: "ଖାତା ଅଛି କି?", loginHere: "ଲଗଇନ୍ କରନ୍ତୁ" },
    landing: { navFeatures: "ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ", navStats: "ଷ୍ଟାଟ୍ସ", navPreview: "ପ୍ରିଭ୍ୟୁ", navSignIn: "ଲଗଇନ୍", navGetStarted: "ଆରମ୍ଭ କରନ୍ତୁ", badge: "ମଡେର୍ନ୍ ଓପନ୍ ସୋର୍ସ ଟ୍ରାକର୍", title1: "ଟ୍ରାକ୍ କରନ୍ତୁ ଆପଣଙ୍କ", typewriter: ["ଓପନ୍ ସୋର୍ସ", "ଗିଟହବ୍", "ଅବଦାନ", "ପ୍ରଭାବ"], title2: "କାର୍ଯ୍ୟ", subtitle: "ଆପଣଙ୍କର ପ୍ରୋଜେକ୍ଟଗୁଡିକ ଏବଂ କାର୍ଯ୍ୟାବଳୀକୁ ସହଜରେ ଟ୍ରାକ୍ କରନ୍ତୁ।", startFree: "ମାଗଣା ଆରମ୍ଭ କରନ୍ତୁ", viewDemo: "ଡେମୋ ଦେଖନ୍ତୁ", builtFor1: "ବିକାଶକାରୀଙ୍କ ନିମନ୍ତେ", builtFor2: "ପ୍ରସ୍ତୁତ", featuresSub: "ଟ୍ରାକ୍ ଏବଂ ଅନୁଶୀଳନ କରିବାର ଶକ୍ତିଶାଳୀ ଉପକରଣ।", f1Title: "ଗିଟହବ୍ ଲଗଇନ୍", f1Desc: "ସୁରକ୍ଷିତ ଏବଂ ଶୀଘ୍ର ଲଗଇନ୍।", f2Title: "ଲାଇଭ୍ ଆନାଲିଟିକ୍ସ", f2Desc: "ସୁନ୍ଦର ଗ୍ରାଫ୍।", f3Title: "ଆକ୍ଟିଭିଟି ମ୍ୟାପ୍", f3Desc: "ଆପଣଙ୍କର କାମ ଦେଖନ୍ତୁ।", f4Title: "JWT ସୁରକ୍ଷା", f4Desc: "ଉନ୍ନତ ସୁରକ୍ଷା।", f5Title: "ତୁରନ୍ତ ଅପଡେଟ୍", f5Desc: "ସବୁ ତଥ୍ୟ ଅପଡେଟ୍ ହେବ।", f6Title: "ଡ୍ୟାସବୋର୍ଡ", f6Desc: "ସବୁ କିଛି ଗୋଟିଏ ସ୍ଥାନରେ।", stat1: "ଅବଦାନ", stat2: "ରିପୋଜିଟୋରୀ", stat3: "ଅପଟାଇମ୍", previewTitle1: "ଏକ ଆକର୍ଷଣୀୟ", previewTitle2: "ଡ୍ୟାସବୋର୍ଡ", navDashboard: "ଡ୍ୟାସବୋର୍ଡ", navAnalytics: "ଆନାଲିଟିକ୍ସ", f2Issues: "ସମସ୍ୟା", stat2Short: "ରିପୋଜିଟୋରୀ", activityGraph: "ଆକ୍ଟିଭିଟି ଗ୍ରାଫ୍", ready1: "ଆପଣ ପ୍ରସ୍ତୁତ କି?", ready2: "ଆଜି ହିଁ ଯୋଗ ଦିଅନ୍ତୁ", join: "OSTracker ସହିତ ନିଜର ଦକ୍ଷତା ପ୍ରମାଣିତ କରନ୍ତୁ।", getStartedNow: "ଯୋଗ ଦିଅନ୍ତୁ" }
  },
  mr: {
    sidebar: { dashboard: "डॅशबोर्ड", repositories: "रिपॉझिटरी", explore: "एक्सप्लोर करा", settings: "सेटिंग्ज" },
    dashboard: { greeting: "स्वागत आहे", subtitle: "प्रकल्प ट्रॅक करा", totalRepos: "पडताळणी केलेले", active: "सक्रिय", completed: "पूर्ण झाले", openIssues: "मुद्दे", recentRepos: "अलीकडील", viewAll: "सर्व पहा", noRepos: "माहिती नाही", addFirst: "सुरू करण्यासाठी जोडा!", language: "भाषा" },
    repoForm: { updateRepo: "अपडेट करा", trackNew: "नवीन ट्रॅक", updateDesc: "तपशील", trackDesc: "तपशील भरा", repoName: "नाव", repoUrl: "URL", language: "भाषा", priority: "प्राधान्य", exploring: "शोधत आहे", active: "सक्रिय", completed: "पूर्ण झाले", notes: "नोंदी", notesPlaceholder: "लिहा...", saveChanges: "जतन करा", trackRepository: "ट्रॅक करा", verifyText: "तपासा" },
    repoList: { health: "आरोग्य", issues: "मुद्दे", stars: "तारे", lastUpdated: "अंतिम अपडेट:", exploring: "शोधत आहे", active: "सक्रिय", completed: "पूर्ण झाले", deleteConfirm: "तुम्हाला खात्री आहे का?", noActiveTitle: "प्रकल्प नाहीत", noActiveDesc: "तुम्ही अद्याप कोणतेही प्रकल्प जोडलेले नाहीत.", trackedRepos: "ट्रॅक केलेले प्रकल्प", total: "एकूण", unknown: "अज्ञात", lastActivity: "शेवटची हालचाल", justNow: "आत्ताच", added: "जोडले", apr2026: "एप्रिल 2026", edit: "संपादित करा", delete: "काढून टाका" },
    login: { title: "स्वागत आहे", passwordMode: "पासवर्ड", otpMode: "OTP", emailPlaceholder: "ईमेल", passwordPlaceholder: "पासवर्ड", signInButton: "साइन इन", enterEmail: "ईमेल", getOtp: "कोड", verifyButton: "तपासा", changeEmail: "ईमेल बदला", resendTimer: "{{time}}s", resendCode: "परत पाठवा", orContinue: "किंवा", githubSignIn: "GitHub", noAccount: "खाते नाही?", registerHere: "नवीन खाते" },
    register: { title: "खाते तयार करा", verifyTitle: "ईमेल तपासा", subtitle: "सामील व्हा", verifySubtitle: "कोड प्रविष्ट करा", username: "नाव", emailPlaceholder: "ईमेल", passwordPlaceholder: "पासवर्ड", sendOtp: "पाठवा", completeBtn: "पूर्ण करा", editDetails: "सुधारा", resendTimer: "{{time}}s", resendCode: "परत", haveAccount: "आधीच खाते आहे?", loginHere: "लॉगिन करा" },
    landing: { navFeatures: "वैशिष्ट्ये", navStats: "आकडेवारी", navPreview: "पूर्वावलोकन", navSignIn: "साइन इन", navGetStarted: "सुरू करा", badge: "आधुनिक ओपन सोर्स ट्रॅकर", title1: "तुमचे", typewriter: ["योगदान", "गिटहब", "प्रकल्प", "काम"], title2: "ट्रॅक करा", subtitle: "तुमच्या प्रकल्पांची प्रगती ट्रॅक करा आणि विश्लेषित करा.", startFree: "मोफत सुरू करा", viewDemo: "डेमो पहा", builtFor1: "विकसकांसाठी", builtFor2: "बनवले", featuresSub: "तुमचे काम विश्लेषित करण्याची साधने.", f1Title: "GitHub लॉगिन", f1Desc: "सोपे आणि सुरक्षित.", f2Title: "लाइव्ह अ‍ॅनालिटिक्स", f2Desc: "डॅशबोर्ड आणि आलेख.", f3Title: "अ‍ॅक्टिव्हिटी हीटमॅप", f3Desc: "गिटहब सारखे डिझाइन.", f4Title: "सुरक्षितता", f4Desc: "JWT संरक्षण.", f5Title: "त्वरित डेटा सिंक", f5Desc: "वेळोवेळी गिटहब डेटा मिळवा.", f6Title: "डॅशबोर्ड", f6Desc: "मल्टी-व्ह्यू रचना.", stat1: "एकूण कमिट", stat2: "प्रकल्प", stat3: "अपटाइम", previewTitle1: "एक सुंदर", previewTitle2: "डॅशबोर्ड", navDashboard: "डॅशबोर्ड", navAnalytics: "विश्लेषण", f2Issues: "मुद्दे", stat2Short: "प्रकल्प", activityGraph: "अ‍ॅक्टिव्हिटी ग्राफ", ready1: "तुम्ही", ready2: "तयार आहात का?", join: "OSTracker सोबत तुमचे काम ट्रॅक करा.", getStartedNow: "आत्ताच सुरू करा" }
  },
  kn: {
    sidebar: { dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", repositories: "ರಿಪೊಸಿಟರಿಗಳು", explore: "ಅನ್ವೇಷಿಸಿ", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು" },
    dashboard: { greeting: "ಸ್ವಾಗತ", subtitle: "ಪ್ರಾಜೆಕ್ಟ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", totalRepos: "ಪರಿಶೀಲಿಸಿದ ರಿಪೋಗಳು", active: "ಸಕ್ರಿಯ", completed: "ಪೂರ್ಣಗೊಂಡಿದೆ", openIssues: "ಸಮಸ್ಯೆಗಳು", recentRepos: "ಇತ್ತೀಚಿನವು", viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ", noRepos: "ಯಾವುದೇ ಮಾಹಿತಿಯಿಲ್ಲ", addFirst: "ಪ್ರಾರಂಭಿಸಿ!", language: "ಭಾಷೆ" },
    repoForm: { updateRepo: "ನವೀಕರಿಸಿ", trackNew: "ಹೊಸ ರಿಪೋ", updateDesc: "ವಿವರಗಳನ್ನು", trackDesc: "ನಮೂದಿಸಿ", repoName: "ಹೆಸರು", repoUrl: "URL", language: "ಭಾಷೆ", priority: "ಆದ್ಯತೆ", exploring: "ಅನ್ವೇಷಿಸಲಾಗುತ್ತಿದೆ", active: "ಸಕ್ರಿಯ", completed: "ಪೂರ್ಣಗೊಂಡಿದೆ", notes: "ಟಿಪ್ಪಣಿಗಳು", notesPlaceholder: "ಬರೆಯಿರಿ...", saveChanges: "ಉಳಿಸಿ", trackRepository: "ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", verifyText: "ಪರಿಶೀಲಿಸಿ" },
    repoList: { health: "ಆರೋಗ್ಯ", issues: "ಸಮಸ್ಯೆಗಳು", stars: "ಸ್ಟಾರ್ಸ್", lastUpdated: "ಕೊನೆಯ ನವೀಕರಣ:", exploring: "ಅನ್ವೇಷಿಸಲಾಗುತ್ತಿದೆ", active: "ಸಕ್ರಿಯ", completed: "ಪೂರ್ಣಗೊಂಡಿದೆ", deleteConfirm: "ನೀವು ಖಚಿತವಾಗಿ ಅಳಿಸಲು ಬಯಸುವಿರಾ?", noActiveTitle: "ಯಾವುದೇ ರಿಪೋಗಳಿಲ್ಲ", noActiveDesc: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ರಿಪೋಗಳನ್ನು ಸೇರಿಸಿಲ್ಲ.", trackedRepos: "ಟ್ರ್ಯಾಕ್ ಮಾಡಿದ ರಿಪೋಗಳು", total: "ಒಟ್ಟು", unknown: "ತಿಳಿದಿಲ್ಲ", lastActivity: "ಕೊನೆಯ ಚಟುವಟಿಕೆ", justNow: "ಈಗ", added: "ಸೇರಿಸಲಾಗಿದೆ", apr2026: "ಏಪ್ರಿಲ್ 2026", edit: "ತಿದ್ದು", delete: "ಅಳಿಸು" },
    login: { title: "ಸ್ವಾಗತ", passwordMode: "ಪಾಸ್‌ವರ್ಡ್", otpMode: "OTP", emailPlaceholder: "ಇಮೇಲ್", passwordPlaceholder: "ಪಾಸ್‌ವರ್ಡ್", signInButton: "ಸೈನ್ ಇನ್", enterEmail: "ಇಮೇಲ್", getOtp: "ಕೋಡ್ ಪಡೆಯಿರಿ", verifyButton: "ಪರಿಶೀಲಿಸಿ", changeEmail: "ಬದಲಾಯಿಸಿ", resendTimer: "{{time}}s", resendCode: "ಮರುಕಳುಹಿಸಿ", orContinue: "ಅಥವಾ", githubSignIn: "GitHub", noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?", registerHere: "ಸೈನ್ ಅಪ್" },
    register: { title: "ಖಾತೆ ರಚಿಸಿ", verifyTitle: "ಪರಿಶೀಲಿಸಿ", subtitle: "ಸೇರಿ", verifySubtitle: "ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ", username: "ಹೆಸರು", emailPlaceholder: "ಇಮೇಲ್", passwordPlaceholder: "ಪಾಸ್‌ವರ್ಡ್", sendOtp: "ಕಳುಹಿಸಿ", completeBtn: "ಪೂರ್ಣಗೊಳಿಸಿ", editDetails: "ತಿದ್ದಿ", resendTimer: "{{time}}s", resendCode: "ಮರುಕಳುಹಿಸಿ", haveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?", loginHere: "ಲಾಗಿನ್ ಮಾಡಿ" },
    landing: { navFeatures: "ವೈಶಿಷ್ಟ್ಯಗಳು", navStats: "ಅಂಕಿಅಂಶಗಳು", navPreview: "ಪೂರ್ವವೀಕ್ಷಣೆ", navSignIn: "ಸೈನ್ ಇನ್", navGetStarted: "ಪ್ರಾರಂಭಿಸಿ", badge: "The Modern Open Source Tracker", title1: "ನಿಮ್ಮ", typewriter: ["ಪ್ರಾಜೆಕ್ಟ್", "GitHub", "ಕೊಡುಗೆ", "ಗಮನ"], title2: "ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", subtitle: "ನಿಮ್ಮ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳನ್ನು ಸುಲಭವಾಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.", startFree: "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ", viewDemo: "ಡೆಮೊ ನೋಡಿ", builtFor1: "ಡೆವಲಪರ್‌ಗಳಿಗಾಗಿ", builtFor2: "ನಿರ್ಮಿಸಲಾಗಿದೆ", featuresSub: "ಉತ್ತಮ ಪರಿಕರಗಳು.", f1Title: "GitHub OAuth", f1Desc: "ಸುಲಭ ಲಾಗಿನ್.", f2Title: "ಲೈವ್ ಅನಾಲಿಟಿಕ್ಸ್", f2Desc: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳು.", f3Title: "ಹೀಟ್‌ಮ್ಯಾಪ್", f3Desc: "ಕಾರ್ಯ ಚಾರ್ಟ್.", f4Title: "ಸುರಕ್ಷತೆ", f4Desc: "JWT ರಕ್ಷಣೆ.", f5Title: "ತ್ವರಿತ ಸಿಂಕ್", f5Desc: "ಡೇಟಾ ನವೀಕರಣ.", f6Title: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", f6Desc: "ಮಲ್ಟಿ-ವ್ಯೂ.", stat1: "ಒಟ್ಟು ಕೊಡುಗೆ", stat2: "ರಿಪೋಗಳು", stat3: "ಅಪ್‌ಟೈಮ್", previewTitle1: "ಸುಂದರವಾದ", previewTitle2: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", navAnalytics: "ಅನಾಲಿಟಿಕ್ಸ್", f2Issues: "ಸಮಸ್ಯೆಗಳು", stat2Short: "ರಿಪೋಗಳು", activityGraph: "ಗ್ರಾಫ್", ready1: "ನೀವು", ready2: "ಸಿದ್ಧರಿದ್ದೀರಾ?", join: "OSTracker ಗೆ ಸೇರಿ.", getStartedNow: "ಈಗಲೇ ಪ್ರಾರಂಭಿಸಿ" }
  }
};

Object.keys(translations).forEach(lang => {
  fs.writeFileSync(`${dir}/${lang}.json`, JSON.stringify(translations[lang], null, 2));
});
